# Generated by Django 5.2.16 on 2026-08-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='action_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='answer',
            name='executive_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='answer',
            name='risk_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
