# Generated by Django 5.2.16 on 2026-08-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_path",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
    ]
