# Generated by Django 5.2.16 on 2026-08-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingvectorcleanup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="pendingvectorcleanup",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="pendingvectorcleanup",
            name="document_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="pendingvectorcleanup",
            name="organization_id",
            field=models.UUIDField(db_index=True),
        ),
    ]
